# Generated by Django 2.2.3 on 2019-07-30 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('vegan', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ingredients', models.ManyToManyField(blank=True, related_name='_recipe_ingredients_+', to='mum_food_test.Ingredient')),
                ('likes', models.ManyToManyField(blank=True, related_name='_recipe_likes_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
